#!/bin/bash

if [ -z $SERIAL_DEVICE ]; then
  SERIAL_DEVICE="/dev/ttyUSB0"
fi

if [ -z $SERIAL_BAUD ]; then
  SERIAL_BAUD="9600"
fi

function usage {
  echo "Usage: $0 on|off 0|1|2|3|4|5|6|7|8|9"
  exit
}

if [ $# -eq 1 ]; then
  case $1 in
    "init")
      screen -S gizmos $SERIAL_DEVICE $SERIAL_BAUD
      ;;

    *)
      usage
  esac
fi

if [ $# -eq 2 ]; then
  case $1 in
    "on")
      screen -S gizmos -X stuff "i$2"
      ;;

    "off")
      screen -S gizmos -X stuff "o$2"
      ;;

    "toggle")
      screen -S gizmos -X stuff "t$2"
      ;;

    *)
      usage
  esac
fi

usage
